apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-boot-k8s
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: vishalkumar392/student-service:1.0.2 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          env:
          - name : config-key
            valueFrom:
               configMapKeyRef:
                    name : config-map
                    key: config-key
          - name : host.docker.internal
            valueFrom:
               configMapKeyRef:
                    name : config-map
                    key: host.docker.internal
          ports:
            - containerPort: 5000 # The port that the container is running on in the cluster